In [1]:
string=' born in 2001/04/05  '
string=string.strip()
print(string.split(' '))
print(string)

['born', 'in', '2001/04/05']
born in 2001/04/05

In [ ]:
#index Slicing
a=list(range(0,11,2))
print(a)
print("{0} a[1:]".format(a[1:]))
print("{0} a[1:3]".format(a[1:3]))
print("{0} a[:-3]".format(a[:-3]))
print("{0} a[::2]".format(a[::2]))
a.remove(6)
print(a)
a.pop(1)
print(a)

[0, 2, 4, 6, 8, 10]
[2, 4, 6, 8, 10] a[1:]
[2, 4] a[1:3]
[0, 2, 4] a[:-3]
[0, 4, 8] a[::2]
[0, 2, 4, 8, 10]
[0, 4, 8, 10]

In [ ]:
#call set
a=set(['a','b','c','c','d'])
b=set(['a','c','e'])
c={'b','d','f'}
print(a,b,c)
#set operations
#set is bit faster when calc and finding
print(a|b|c)
print(a&b)
print(a-b)
d=a|b|c
d=sorted(d)
print(d)
print(sorted(a|b|c))

{'c', 'a', 'd', 'b'} {'e', 'a', 'c'} {'d', 'f', 'b'}
{'e', 'a', 'd', 'b', 'f', 'c'}
{'a', 'c'}
{'d', 'b'}
['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
            [7,8,9]])

#slicing only==>follows original rank else:needed rank
#change in sliced arrays affect original array
print(arr.shape)
print(arr)
print(arr[1,2])
print(arr[1][2])
print(arr[1][1])
print(arr[0:3][0:3])
print(arr[0:2][0:2])
print(arr[1,:3])
print(arr[1,0:3])
print(arr[1:2,0:3])
print(arr[:,0])
print(arr[:,0:1])
print(arr[0:3,0:1])
print(arr[0:3,0])

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
6
5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[4 5 6]
[4 5 6]
[[4 5 6]]
[1 4 7]
[[1]
 [4]
 [7]]
[[1]
 [4]
 [7]]
[1 4 7]

In [ ]:
import numpy as np
zeros=np.zeros((3,4))
print(zeros)
sixsixsix=np.full((3,4),6)
print(sixsixsix)
Diag=np.eye(2,2)
print(Diag)
Ones=np.ones((3,4))
print(type(Ones[0][1]))
print(Ones)
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[(arr%2==0)]) #filter should be includede inside ()
print(arr%2==0) #whether elements are even or not
print(arr)
arr[(arr%2==0)]+=10 #only does +10 for elements%2==0
print(arr)
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr.mean()) #all elements
print(arr.mean(axis=0)) #mean of columns
print(arr.mean(axis=1)) #mean of rows
print(arr.sum(axis=0)) #sum of columns
print(np.median(arr,axis=0)) #median for columns
#By adding dtype=~ for claiming new array ==> datatype for all elements

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
[[1. 0.]
 [0. 1.]]
<class 'numpy.float64'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[2 4 6 8]
[[False  True False]
 [ True False  True]
 [False  True False]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1 12  3]
 [14  5 16]
 [ 7 18  9]]
5.0
[4. 5. 6.]
[2. 5. 8.]
[12 15 18]
[4. 5. 6.]

In [ ]:
import numpy as np
rnd=np.random.random((2,3)) #0~1 random
print(rnd)
rnd2=np.random.randn(2,3) #mean:0, std:1 random
print(rnd2)
arr=np.array([[1,7,3],
            [4,2,5],
            [3,1,1]])
print(np.sort(arr)) #sort ascending in rows
print(np.sort(arr,axis=0)) #sort ascending in columns
print(np.sort(arr,axis=1))#sort ascending in rows
#[::-1]==>descending
print(np.sort(arr,axis=0)[::-1])
print(np.unique(arr))
print(type(np.unique(arr))) #print all unique elements in array form

[[0.42878647 0.10501787 0.63980625]
 [0.70536823 0.8471282  0.70716758]]
[[ 0.74426466 -0.26548385  1.47652159]
 [-0.36780175  0.1550016   0.69617018]]
[[1 3 7]
 [2 4 5]
 [1 1 3]]
[[1 1 1]
 [3 2 3]
 [4 7 5]]
[[1 3 7]
 [2 4 5]
 [1 1 3]]
[[4 7 5]
 [3 2 3]
 [1 1 1]]
[1 2 3 4 5 7]
<class 'numpy.ndarray'>

In [ ]:
A=np.array([1,2,3,4,5,6])
B=A.reshape(2,3)
C=B.T
print(A)
print(B)
print(C)
a=np.array([[1,2,3],
          [4,5,6]])
b=np.array([[7,8,9],
          [10,11,12]])
print(np.vstack((a,b))) #vertical stacking
print(np.hstack((a,b))) #horizonal
np.concatenate([a,b],axis=0)#vertical

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
import pandas as pd
df = pd.DataFrame([
    [0.061038, 1.339673],
    [np.nan, np.nan],
    [1.578293, 0.637435],
    [np.nan, np.nan],
    [np.nan, np.nan],
    [np.nan, np.nan],
    [np.nan, np.nan],
    [np.nan, np.nan],
    [np.nan, np.nan],
    [-1.145787, 0.052887]
])
df.fillna(method='bfill') #fill na from behind values

<ipython-input-18-61d1895642b6>:14: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill') #fill na from behind values

          0         1
0  0.061038  1.339673
1  1.578293  0.637435
2  1.578293  0.637435
3 -1.145787  0.052887
4 -1.145787  0.052887
5 -1.145787  0.052887
6 -1.145787  0.052887
7 -1.145787  0.052887
8 -1.145787  0.052887
9 -1.145787  0.052887

In [ ]:
df.fillna(method='ffill')#take value from above and fill

<ipython-input-19-22fa09078845>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')#take value from above and fill

          0         1
0  0.061038  1.339673
1  0.061038  1.339673
2  1.578293  0.637435
3  1.578293  0.637435
4  1.578293  0.637435
5  1.578293  0.637435
6  1.578293  0.637435
7  1.578293  0.637435
8  1.578293  0.637435
9 -1.145787  0.052887

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame([
    [np.nan, np.nan, -0.335410],
    [np.nan, np.nan, 0.685743],
    [0.077005, 0.085073, 0.565144],
    [0.394961, -1.829587, 0.494039],
    [1.486227, -0.480726, -0.127278],
    [np.nan, np.nan, -0.047668],
    [np.nan, np.nan, -1.504804],
    [-0.530518, -0.881817, -2.687352],
    [0.825376, 1.042468, -0.311527],
    [0.097617, 1.373572, -0.682435]
])
print(df.dropna()) #drops rows with NaN
print(df.dropna(axis=1)) #drop columns with NaN

          0         1         2
2  0.077005  0.085073  0.565144
3  0.394961 -1.829587  0.494039
4  1.486227 -0.480726 -0.127278
7 -0.530518 -0.881817 -2.687352
8  0.825376  1.042468 -0.311527
9  0.097617  1.373572 -0.682435
          2
0 -0.335410
1  0.685743
2  0.565144
3  0.494039
4 -0.127278
5 -0.047668
6 -1.504804
7 -2.687352
8 -0.311527
9 -0.682435

In [ ]:
import pandas as pd
df = pd.DataFrame([1,2,3,4,5])
df2 = pd.DataFrame([6,7,8,9,10])
print(pd.concat([df,df2])) #axis=0 default=> vertical, axis=1 =>horizonal

    0
0   1
1   2
2   3
3   4
4   5
0   6
1   7
2   8
3   9
4  10

In [2]:
import pandas as pd
import numpy as np
student=pd.DataFrame({
    "ID": [1557, 88848, 625],
    "Name": ['Faker','Chovy','Pig'],
    'Sex': ['M','M','M'],
})
print((student['Sex']=='M').all()) #all Sex=M ==>True
print((student['Name']=='Faker').all()) #all Name =/=Faker==>False
print((student['ID']==1557).any()) #there is ID 1557 ==>True
new=student.replace('M','F') #Not Saving
print(student)
print(new)

True
False
True
      ID   Name Sex
0   1557  Faker   M
1  88848  Chovy   M
2    625    Pig   M
      ID   Name Sex
0   1557  Faker   F
1  88848  Chovy   F
2    625    Pig   F

In [4]:
import pandas as pd
import numpy as np
student=pd.DataFrame({
    "ID": [1557, 88848, 625],
    "Name": ['Faker','Chovy','Pig'],
    'Sex': ['M','M','M'],
})
teacher=pd.DataFrame({
    "ID": [108, 2001,666],
    "Name": ['bud','Paul','devil'],
    'Major':['sleeping','killing','villan'],
})
print(student[student['ID']>600]) #returned Data with ID>600
student['Gamer']=[True,True,False] #simply declare new columns
print(student)
student.loc[4]=[999,'chicken','F',False]  #if data 4 exists, it replaces, else save in this format n ~ ~ ~...
print(student)
print(pd.concat([student,teacher])) #index number doesnt change, leaves NaN for missing ones
#pd.merge(A,B,how=~): joins A and B together, left: A rules right:B rules, inner:only same values, outer:all values col='' =>that col rules
print(student.replace('M','Male')) #replaced m to Male
print(student['Sex'].str.contains('F')) #does it contain 'F' for column 'Sex'? str.split usable as well

      ID   Name Sex
0   1557  Faker   M
1  88848  Chovy   M
2    625    Pig   M
      ID   Name Sex  Gamer
0   1557  Faker   M   True
1  88848  Chovy   M   True
2    625    Pig   M  False
      ID     Name Sex  Gamer
0   1557    Faker   M   True
1  88848    Chovy   M   True
2    625      Pig   M  False
4    999  chicken   F  False
      ID     Name  Sex  Gamer     Major
0   1557    Faker    M   True       NaN
1  88848    Chovy    M   True       NaN
2    625      Pig    M  False       NaN
4    999  chicken    F  False       NaN
0    108      bud  NaN    NaN  sleeping
1   2001     Paul  NaN    NaN   killing
2    666    devil  NaN    NaN    villan
      ID     Name   Sex  Gamer
0   1557    Faker  Male   True
1  88848    Chovy  Male   True
2    625      Pig  Male  False
4    999  chicken     F  False
0    False
1    False
2    False
4     True
Name: Sex, dtype: bool

In [5]:
names = ['Bulbasaur', 'Charmander','Squirtle']
hps = [45, 39,44]
combined =[]
for i,pokemon in enumerate(names):  #enumerate==>return (index number, element) tuple
  combined.append((pokemon,hps[i]))
print(combined)
zipped=zip(names,hps) #zip_type, should convert to list
zipped_list=[*zipped]
zipped_list

[('Bulbasaur', 45), ('Charmander', 39), ('Squirtle', 44)]

[('Bulbasaur', 45), ('Charmander', 39), ('Squirtle', 44)]

In [6]:
import pandas as pd
import numpy as np
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')
print(chipo.shape[0])#how many raws do we have
print(chipo.shape[1])#how many columns do we have
C=chipo.groupby(['item_name']).sum() #first grouped by item name=>simply sum it =>order id, item_price was simply appended and summed
C.head(5)

4622
5

,order_id,quantity,choice_description,item_price
item_name,,,,
6 Pack Soft Drink,52322,55,[Sprite][Diet Coke][Coke][Diet Coke][Diet Coke...,$6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.49 $6.4...
Barbacoa Bowl,53972,66,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75 $11.75 $9.25 $8.99 $9.25 $11.75 $9.25 $...
Barbacoa Burrito,74718,91,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99 $9.25 $9.25 $11.75 $11.75 $9.25 $8.99 $1...
Barbacoa Crispy Tacos,5613,12,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.75 $9.25 $11.48 $11.75 $9.25 $9.25 $8.99 $...
Barbacoa Salad Bowl,9708,10,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89 $11.89 $9.39 $9.39 $9.39 $11.89 $11.89 ...

In [ ]:
#A.~.apply()==>apply fucntions to ~
orders=chipo.order_id.value_counts()#count how many times order_id appeared for each(order_id 926 ordered 23 different menus)
orders

order_id
926     23
1483    14
205     12
759     11
1786    11
        ..
768      1
341      1
1048     1
94       1
1199     1
Name: count, Length: 1834, dtype: int64

In [7]:
from collections import Counter
counter= Counter('kyuukurarin')
other= Counter('Kyaururung')
counter#shows each elements number
counter.subtract(other) #numbers of each from counter - numbers from other
counter.update(other) #add numbers
print(counter)
del(counter['u'])
print(counter) #erase all 'u'
elements = counter.elements()  # doesn't return elements with count 0 or less
for value in elements:
    print(value)

Counter({'u': 3, 'k': 2, 'r': 2, 'y': 1, 'a': 1, 'i': 1, 'n': 1, 'K': 0, 'g': 0})
Counter({'k': 2, 'r': 2, 'y': 1, 'a': 1, 'i': 1, 'n': 1, 'K': 0, 'g': 0})
k
k
y
r
r
a
i
n

In [8]:
chipo['item_price']=chipo['item_price'].apply(lambda x: float(x[1:])) # to detach $from it, we should omit x[0] and apply cast changer, float
chipo.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [10]:
names=['kim','lee']
age=[10,12]
zipped=zip(names,age)
zipped_list=[*zipped] #Combined by tuple
zipped_list

[('kim', 10), ('lee', 12)]

In [ ]:
from collections import Counter
counter= Counter('kyuukurarin')
other= Counter('Kyaururung')
counter#shows each elements number
counter.subtract(other) #numbers of each from counter - numbers from other
counter
counter.update(other) #add numbers
print(counter)
del(counter['u'])
print(counter) #erase all 'u'
elements = counter.elements()  # doesn't return elements with count 0 or less
for value in elements:
    print(value)

Counter({'u': 3, 'k': 2, 'r': 2, 'y': 1, 'a': 1, 'i': 1, 'n': 1, 'K': 0, 'g': 0})
Counter({'k': 2, 'r': 2, 'y': 1, 'a': 1, 'i': 1, 'n': 1, 'K': 0, 'g': 0})
k
k
y
r
r
a
i
n

In [ ]:
from functools import reduce
target = list(range(1, 21))
print(reduce(lambda x, y: x + y, target))  #reduce returns final result of all x+y

210

In [ ]:
from itertools import combinations
names=['a','b','c','d']
comb=combinations(names,2) #all combinations 4C2
comb_=[*comb]
print(comb_)

[('a', 'b'), ('a', 'c'), ('a', 'd'), ('b', 'c'), ('b', 'd'), ('c', 'd')]

In [ ]:
# zip(a,b) ==> return tupel (a[0],b[0])(a[1],b[1])...
#map(a,b) ==> apply a to all elements in b and return
#[*zip(a,b)]==> [(a[0],b[0])..]
from functools import reduce
target = list(range(1, 21))
print(reduce(lambda x, y: x + y, target))  #reduce returns final result of all x+y

210

In [ ]:
class Bottle(object): #Python 2~ object was necessary
    def __init__(self, quantity):
        self.__quantity = quantity

    def fill(self, quantity):
        if self.__quantity + quantity > 100:
            self.__quantity = 100
        else:
            self.__quantity += quantity
    def show(self):
      print(self.__quantity)
# __~==> private parameters, must start with __init__ and self for parameters and functions
class CokeBottle(Bottle):
  def __init__(self,quantity,taste):
    super().__init__(quantity) #use parent's class init
    self.__taste=taste
  def show(self):
    super().show() #use parent's class init
    print(self.__taste)

btl1=Bottle(30)
btl2=CokeBottle(20,'chilling') #inherited Bottle => same method can be used including __init__/=
btl1.fill(30)
btl2.fill(70)
btl1.show()
btl2.show()

60
90
chilling

In [ ]:
class BaseballPlayer():
    def __init__(self, name):
        self.name = name

    def play(self):
        print(self.name, 'play baseball')

class BasketballPlayer():
    def __init__(self, name):
        self.name = name

    def play(self):
        print(self.name, 'play basketball')

b1 = BaseballPlayer('aaron')
b11 = BasketballPlayer('sam')
players = [b1, b11]

for player in players: #if they have same name function ==>loop available
    player.play()

In [ ]:
class Employee(object):
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def __str__(self):
        return 'name : {}, salary = {}'.format(self.name, self.salary)

    def __repr__(self):
        return 'name : {}, salary = {}'.format(self.name, self.salary)

    def __add__(self, other):
        if type(other) == int:
            new_emp = Employee(self.name, self.salary + other)
        else:
            new_emp = Employee(self.name + other.name, self.salary + other.salary)
        return new_emp

    def __radd__(self, other):
        return Employee(self.name, self.salary + other)

    def __len__(self):
        return len(self.name)

    def __gt__(self, other): # greater than
        print ("__gt__ is called")
        return self.salary > other.salary

    def __gte__(self, other): # equal
        print ("__gte__ is called")
        return self.salary >= other.salary

    def __lt__(self, other): # less than, it appears 5 times as
        print ("__lt__ is called")
        return self.salary < other.salary

    def __lte__(self, other):
        print ("__lte__ is called")
        return self.salary <= other.salary

    def __eq__(self, other):
        print ("__eq__ is called")
        return len(self.name) == len(other.name)
e1 = Employee('bob', 1000)
e2 = Employee('kate', 2000)
e3 = Employee('ken', 2500)
e4 = Employee('fox', 500)
print(e1 + e2)
print(e1 + e2 + e3)
print(e1 + 1000) #this will call '__add__', As intergers will be added to salary for __add__
print(1000 + e1)
print(len(e1))
print ("="*50)
lst = [e1, e4, e2, e3]
print(e1 < e2)
print ()
print(sorted(lst)) #to sort list, calculate e1>e2, e2>e3....=>5 times 'less than' < was called
print ()
print(sorted(lst, key=lambda x : x.salary)) #the key was given by x.salary so no other metods are needed to sort
print ()
print(e1 == e3)
print(e1 == e2)

name : bobkate, salary = 3000
name : bobkateken, salary = 5500
name : bob, salary = 2000
name : bob, salary = 2000
3
==================================================
__lt__ is called
True

__lt__ is called
__lt__ is called
__lt__ is called
__lt__ is called
__lt__ is called
[name : fox, salary = 500, name : bob, salary = 1000, name : kate, salary = 2000, name : ken, salary = 2500]

[name : fox, salary = 500, name : bob, salary = 1000, name : kate, salary = 2000, name : ken, salary = 2500]

__eq__ is called
True
__eq__ is called
False

In [ ]:
from itertools import combinations
names=['a','b','c','d']
comb=combinations(names,2) #all combinations 4C2
comb_=[*comb]
print(comb_)

[('a', 'b'), ('a', 'c'), ('a', 'd'), ('b', 'c'), ('b', 'd'), ('c', 'd')]

''Pandas.merge: merges dataframe''

In [ ]:
import pandas as pd
capitals = pd.DataFrame(
    {'Country':['Afghanistan','Argentina','Australia','Canada','China','France','India','Nepal','Russia','Spain'],
     'ISO' : ['AF','AR','AU','CA','CN','FR','IN','NP','RU','ES'],
     'Capital' : ['Kabul','Buenos_Aires','Canberra','Ottawa','Beijing','Paris','New_Delhi','Katmandu','Moscow','Madrid'] },
    columns=['Country', 'ISO', 'Capital'])
# Country and its currencies
currency = pd.DataFrame(
    {'Country':['France','India','Nepal','Russia','Spain','Sri_Lanka','United_Kingdom','USA','Uzbekistan','Zimbabwe'],
     'Currency' : ['Euro','Indian_Rupee','Nepalese_Rupee','Rouble','Euro','Rupee','Pound','US_Dollar','Sum_Coupons','Zimbabwe_Dollar'],
     'Digraph' : ['FR','IN','NP','RU','ES','LK','GB','US','UZ','ZW'] },
    columns=['Country', 'Currency', 'Digraph'])
print(pd.merge(left = capitals,right = currency, how = 'inner'))
print()
print(pd.merge(left = capitals,right = currency,how = 'inner',on = 'Country'))
print()
#want to sort by ticker, but column name is differnent, so declare each one
print(pd.merge(left = capitals,right = currency,how= 'inner',left_on='ISO',right_on='Digraph'))
print()
#default suffix for duplicate =>_x, _y / manually change by suffixes
print(pd.merge(left = capitals,right = currency,how= 'inner',left_on='ISO',right_on='Digraph',suffixes=['_left','_right']))

  Country ISO    Capital        Currency Digraph
0  France  FR      Paris            Euro      FR
1   India  IN  New_Delhi    Indian_Rupee      IN
2   Nepal  NP   Katmandu  Nepalese_Rupee      NP
3  Russia  RU     Moscow          Rouble      RU
4   Spain  ES     Madrid            Euro      ES

  Country ISO    Capital        Currency Digraph
0  France  FR      Paris            Euro      FR
1   India  IN  New_Delhi    Indian_Rupee      IN
2   Nepal  NP   Katmandu  Nepalese_Rupee      NP
3  Russia  RU     Moscow          Rouble      RU
4   Spain  ES     Madrid            Euro      ES

  Country_x ISO    Capital Country_y        Currency Digraph
0    France  FR      Paris    France            Euro      FR
1     India  IN  New_Delhi     India    Indian_Rupee      IN
2     Nepal  NP   Katmandu     Nepal  Nepalese_Rupee      NP
3    Russia  RU     Moscow    Russia          Rouble      RU
4     Spain  ES     Madrid     Spain            Euro      ES

  Country_left ISO    Capital Country_right        Currency Digraph
0       France  FR      Paris        France            Euro      FR
1        India  IN  New_Delhi         India    Indian_Rupee      IN
2        Nepal  NP   Katmandu         Nepal  Nepalese_Rupee      NP
3       Russia  RU     Moscow        Russia          Rouble      RU
4        Spain  ES     Madrid         Spain            Euro      ES

In [ ]:
import pandas as pd
sales=pd.DataFrame({
    'weekday':['Sun','Sun','Mon','Mon'],
    'city':['Austin','Dallas','Austin','Dallas'],
    'bread':[100,200,300,400],
    'butter':[20,30,40,50],
})
def data_range(series):
  return series.max()-series.min()
def z_scores(series): #calculate for z-scores
  return (series-series.mean())/series.std()
print(sales.groupby('weekday').count()) #grouped by weekday, city's each sale for each day, how many entry?
print(sales.groupby('weekday')['bread'].sum()) #For each weekday, how many bread sold?
print(sales.groupby(['weekday','city'])['bread'].sum()) #==>consider groupby('[]') as setting index with certain column
print(sales['weekday'].unique()) #seek unique value by a['column'].unique
print(sales.groupby('city')[['bread','butter']].agg(['max','sum'])) #grouped by city, for bread and butter, print out max and sum for each
print(sales.groupby('weekday')[['bread','butter']].agg(data_range))
print(sales.groupby('weekday')[['bread','butter']].agg({'bread':'sum', 'butter':data_range})) #How to use agg
print(sales.groupby('city'))
print(sales[(sales['city']=='Austin')&(sales['bread']>150)])
#by apply, we should choose column that function available, transform dont require
#groupby==>type: DataFrameGroupBy dont print out any value, groupby.groups()==>dict

         city  bread  butter
weekday
Mon         2      2       2
Sun         2      2       2
weekday
Mon    700
Sun    300
Name: bread, dtype: int64
weekday  city
Mon      Austin    300
         Dallas    400
Sun      Austin    100
         Dallas    200
Name: bread, dtype: int64
['Sun' 'Mon']
       bread      butter
         max  sum    max sum
city
Austin   300  400     40  60
Dallas   400  600     50  80
         bread  butter
weekday
Mon        100      10
Sun        100      10
         bread  butter
weekday
Mon        700      10
Sun        300      10
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7ae420afc0d0>
  weekday    city  bread  butter
2     Mon  Austin    300      40

In [ ]:
import pandas as pd

df=pd.DataFrame({'store':['Costco','Costco','Costco','Wal-Mart','Wal-Mart','Wal-Mart',"Sam's Club","Sam's Club","Sam's Club"],
               'product':['Potato','Onion','Cucumber','Potato','Onion','Cucumber','Potato','Onion','Cucumber'],
               'price':[3000,1600,2600,3200,1200,2100,2000,2300,3000],
                'quantity':[25,31,57,32,36,21,46,25,9]})
print(df)
new_df=df.melt(id_vars=['product','store'],var_name='product_info',value_name='product_value')
print(new_df)
new_pivot=df.pivot(index='product',columns='store',values='price')
print(new_pivot)

        store   product  price  quantity
0      Costco    Potato   3000        25
1      Costco     Onion   1600        31
2      Costco  Cucumber   2600        57
3    Wal-Mart    Potato   3200        32
4    Wal-Mart     Onion   1200        36
5    Wal-Mart  Cucumber   2100        21
6  Sam's Club    Potato   2000        46
7  Sam's Club     Onion   2300        25
8  Sam's Club  Cucumber   3000         9
     product       store product_info  product_value
0     Potato      Costco        price           3000
1      Onion      Costco        price           1600
2   Cucumber      Costco        price           2600
3     Potato    Wal-Mart        price           3200
4      Onion    Wal-Mart        price           1200
5   Cucumber    Wal-Mart        price           2100
6     Potato  Sam's Club        price           2000
7      Onion  Sam's Club        price           2300
8   Cucumber  Sam's Club        price           3000
9     Potato      Costco     quantity             25
10     Onion      Costco     quantity             31
11  Cucumber      Costco     quantity             57
12    Potato    Wal-Mart     quantity             32
13     Onion    Wal-Mart     quantity             36
14  Cucumber    Wal-Mart     quantity             21
15    Potato  Sam's Club     quantity             46
16     Onion  Sam's Club     quantity             25
17  Cucumber  Sam's Club     quantity              9
store     Costco  Sam's Club  Wal-Mart
product
Cucumber    2600        3000      2100
Onion       1600        2300      1200
Potato      3000        2000      3200

In [ ]:
plt.axes([x,y,width,height])
plt.subplot(2,1,1)
plt.xlabel, plt.title, plt.tight_layout()
plt.xlim((min,max))/ plt.ylim((min,max)) / plt.axis((xmin,xmqx,ymin,ymax)) / axis(): equal equal scaling square, off, tight
plt.scatter(a,b,marker='',color='',label='')
plt.legend(loc='upper right') put legends on upper right
plt.annotate('label',xy=(),xy,text=(),arrowprops={'color':'red'}) given coordinates, put 'label' with arrows with red color

xy: directed point coord/ xytext: coord of text

SyntaxError: illegal target for annotation (<ipython-input-41-201fd6dfb3ab>, line 4)

In [ ]:
import pandas as pd
#--------------------------------------------------------------------------------------------#
#Resampling & concatenating DataFrames with inner join
china = pd.read_csv("datasets/GDP/gdp_china.csv", parse_dates=['Year']) #Read Year Column as "DateTime Format"
china.rename(columns={'GDP': 'China'}, inplace=True) # renaming the name of the column GDP => China
china.set_index('Year', inplace=True) #Year column becomes index
print(china.head(5))
us = pd.read_csv("datasets/GDP/gdp_usa.csv", parse_dates=['DATE'])
us.rename(columns={'DATE': 'Year', 'VALUE': 'US'}, inplace=True)
us.set_index('Year', inplace=True)
print(us.index.strftime('%b %d'))
print(us.head(5))

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/GDP/gdp_china.csv'

In [ ]:
china_annual = china.resample('A').last().pct_change(10).dropna()
china_annual2 = china.resample('2A').last().pct_change(20).dropna()
print(china.head(5))
print(china.resample('2A').first().head(10)) #gets data from above 1962=>1961-01-01
print(china.resample('2A').last().head(10)) #gets dat from below 1962<=1962-01-01
# A: Annually samples , 2A: for every 2 years. last(), pct_change(10)==>new 2009=(2009-1999/1999)*100
# first()=> gets data from above, last()=>from below

In [ ]:
import pandas as pd
sp500 = pd.read_csv('sp500.csv',parse_dates=['Date'])
sp500.info()
sp500 = sp500.set_index('Date')
sp500=sp500.sort_index()
print(sp500.head(5))
print(sp500.info())

In [ ]:
print(sp500.loc['2021-12-01': '2021-12-10'])
print(sp500.iloc[1:]) #difference btw them, as called 1:, it will print out all except for [0]

In [ ]:
sp500_1w_resample = sp500.resample(rule='1W-FRI').last()
print(sp500_1w_resample.head(5))
sp500_1w_asfreq = sp500.asfreq('1W-FRI')
sp500.resample('1W-FRI').agg({'Open': 'first', 'High': 'max', 'Low': 'min', 'Close': 'last', 'Volume': 'sum'})
#each column was applied each method

In [ ]:
sp500.asfreq('1D').fillna(method='ffill').head(10)

In [ ]:
sp500['Close'].rolling(window=3, min_periods=1).mean() #average of 3 entries, but if it's only 1 or 2, calculate in them
#min periods 2 will return NaN for first day as it requires 2 at least

In [ ]:
sp500['Close_previous_3'] = sp500['Close'].shift(periods=3)
sp500['Close_previous_3'] #As period is 3, it pushed 3 times downward. upward when negative

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
filename = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
headers = ["symboling","normalized-losses","make","fuel-type","aspiration", "num-of-doors","body-style",
         "drive-wheels","engine-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "num-of-cylinders", "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
         "peak-rpm","city-mpg","highway-mpg","price"]
df = pd.read_csv(filename, names = headers)
df.replace("?", np.nan, inplace = True)
print(df.isnull().head(5))
# calculate the mean vaule for "stroke" column
avg_stroke = df["stroke"].astype("float").mean(axis = 0)
print("Average of stroke:", avg_stroke)

# replace NaN by mean value in "stroke" column
df["stroke"].replace(np.nan, avg_stroke, inplace = True)

In [ ]:
df[["bore", "stroke"]] = df[["bore", "stroke"]].astype("float")
df[["price"]] = df[["price"]].astype("float")
df[["peak-rpm"]] = df[["peak-rpm"]].astype("float")
# transform mpg to L/100km by mathematical operation (235 divided by mpg)
df["highway-mpg"] = 235/df["highway-mpg"]
print(df['num-of-doors'].value_counts().idxmax()) #shows mode of data ==> as idxmax shows the biggest value from "value_counts()"
# rename column name from "highway-mpg" to "highway-L/100km"
df.rename(columns={'"highway-mpg"':'highway-L/100km'}, inplace=True)

dummy_variable_1 = pd.get_dummies(df["fuel-type"]) #From category fuel type, derive two types and convert to bool column
print('dummy)applied')
print(dummy_variable_1.head())
# merge data frame "df" and "dummy_variable_1"
df = pd.concat([df, dummy_variable_1], axis=1) #by column, horizionally
# drop original column "fuel-type" from "df"
df.drop("fuel-type", axis = 1, inplace=True)

print(df.head(5))

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
titanic = sns.load_dataset('titanic')
sns.set_style('whitegrid')
# 차트 가로로 그리기 : x를 y로 변경하면 세로에서 가로 차트로 변경 가능
sns.countplot(y="class", hue="who", data=titanic)

In [ ]:
x = np.random.randn(1000) # normalize
sns.distplot(x, hist=True, kde=True)
plt.show()

In [ ]:
heatmap_data = np.random.rand(10, 10)
sns.heatmap(heatmap_data, annot=True) #annot=True로 해야 수치 표현도 가능 # annotation

In [ ]:
tips = sns.load_dataset('tips')
# hue 옵션으로 구분해서 볼수도 있다.
sns.pairplot(tips, hue='size') #kind='reg'
plt.show()
# violinplot의 하이라이트로 split 옵션으로 바이올린을 합쳐서 볼 수 있다.
sns.violinplot(x="day", y="total_bill", hue="smoker", data=tips, palette="muted", split=True)
sns.violinplot(x="day", y="total_bill", hue="smoker", data=tips, palette="muted", split=True)
plt.show()

In [ ]:
# col_wrap으로 한 줄에 표기할 column의 갯수를 명시할 수 있다.
sns.lmplot(x='total_bill', y='tip', hue='smoker', col='day', data=tips) #linear regression+scatter
plt.show()

In [ ]:
# 옵션에 kind='reg'을 추가
sns.jointplot(x="total_bill", y="tip", data=tips, kind="reg") # regression kind='hex'
plt.show()

In [ ]:
sns.stripplot(x='day',y='tip',data=tips,jitter=True) #jitter spreads

In [ ]:
sns.swarmplot(x='day',y='tip',data=tips,hue='sex')

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
df = pd.read_csv("datasets/Olympics/Summer-Olympic-medals-1976-to-2008.csv",encoding_errors='ignore')
sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 12
matplotlib.rcParams['figure.figsize'] = (9, 5)
matplotlib.rcParams['figure.facecolor'] = '#00000000'
top_countries = df['Country'].value_counts().sort_values(ascending=False).head(10)
plt.figure(figsize=(8,4))
plt.xticks(rotation=75)
plt.title('Overall Participation Countrywise')
sns.barplot(x=top_countries.index, y=top_countries);

In [ ]:
df_medal_holders = df[df.Medal !='None']
df_medal_holders['Count_Of_Medals'] = 1
df_medal_holders.head()
df_highest_medals = df_medal_holders[['Athlete', 'Year', 'Country', 'Count_Of_Medals']].groupby(['Athlete','Year','Country']).sum().sort_values('Count_Of_Medals', ascending=False)
df_highest_medals.reset_index(inplace=True)
df_highest_medals

In [ ]:
gender_counts = df.Gender.value_counts()
gender_counts
plt.figure(figsize=(10,5))
plt.title('Gender Distribution')
plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=180)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.distributions.empirical_distribution import ECDF
#np.random.random=>draws num btw 0~1 np.random.seed() => fix a random number by a certain 'seed'
np.random.seed(42)
random_nums=np.random.random(size=4)
print(random_nums)
heads=random_nums<0.5
print(heads)
#Bernoulli Trial => T/F (Binomial Trial)
print(np.random.binomial(4,0.5,size=100)) #n trials, prob:0.5, 100 cases=>400 throwings
#CDF(Cumulative distribution function)
sns.set()
x=ECDF(np.random.binomial(4,0.5,size=100)).x
y=ECDF(np.random.binomial(4,0.5,size=100)).y
plt.plot(x,y,marker='.',linestyle='none')
plt.margins(0.02)

#Poisson distribution: independent, time..
#numbr of hits on a website in one hour, average hit rate of 6hits per hour

sns.set()
x=ECDF(np.random.poisson(4,size=100)).x
y=ECDF(np.random.poisson(4,size=100)).y
plt.plot(x,y,marker='.',linestyle='none')
plt.margins(0.02)
#random.exponential available
#check normality data by compare original data and data sampled by mean and std of original data

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from math import factorial, exp

plt.subplot(3, 1, 1)
plt.xlim(0, 40)
plt.ylim(0, 300)
pd1 = np.random.poisson(10, 1000)
plt.text(33.5, 250, 'lamb=10')
plt.hist(pd1, color='lightcoral')

plt.subplot(3, 1, 2)
plt.xlim(0, 40)
plt.ylim(0, 300)
pd2 = np.random.poisson(15, 1000)
plt.text(33.5, 250, 'lamb=15')
plt.hist(pd2, color='mediumaquamarine')

plt.subplot(3, 1, 3)
plt.xlim(0, 40)
plt.ylim(0, 300)
pd3 = np.random.poisson(20, 1000)
plt.text(33.5, 250, 'lamb=20')
plt.hist(pd3, color='royalblue')

plt.show()

In [ ]:
# Import plotting modules
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

# Set default Seaborn style
sns.set()

from sklearn.datasets import load_iris # scikit-learn

data = load_iris()

In [ ]:
plt.axes([x,y,width,height])
plt.subplot(2,1,1) #(2*1, divide area in two parts, this selects first rect)
plt.xlabel, plt.title, plt.tight_layout() #this replaces layout
plt.xlim((min,max))/ plt.ylim((min,max)) / plt.axis((xmin,xmqx,ymin,ymax)) / axis(): equal)equal scaling square, off, tight
plt.scatter(a,b,marker='',color='',label='') / plt.hist(y, bins=20)
plt.legend(loc='upper right') #put legends on upper right
plt.annotate('label',xy=(),arrowprops{'color':'red'}) #given coordinates, put 'label' with arrows with red color

From - To]

[abc]==>This means does word have a or b or c

Using a hyphen (-) between the two characters in [ ] means the range (From - To) between the two characters. For example, the regular expression [a-c] is the same as [abc], and [0-5] is the same as [012345].

^

When ^ metacharacter is used inside [], it has the meaning of "not". The regular expression [^0-9] matches only non-numeric character

***"Capitalization of below becomes "not"~"***

**\d**

same as the [0-9]

**\s**

matches whitespace character same as the [ \t\n\r\f\v]

**\w**

same as the [a-zA-Z0-9_]  (number+numeric)


**Asterisk(*)**

means that the character immediately preceding the * can berepeated from 0 to infinity

**+**

means that the character immediately preceding the + can be repeated from 1 to infinity

In [ ]:
import re
re.compile('^wp.*\.php$')
abc=re.compile('[abc]') #if there is a/b/c > return true
joke=re.compile('^joke.*mc$')
print(bool(joke.search("joke mc")))
print(re.findall())
print(bool(joke.search("joke you")))
print(bool(abc.search('apple'))) #contains a>True
print(bool(abc.search('deer'))) #contains none of them >False
ab=re.compile('a.b')#. means any character except /n
print(bool(ab.search('a33b')))
print()
p = re.compile("\w+\s+\d+[-]\d+[-]\d+")
print (bool(p.search("park 010-1234-1234"))) #\w: park/ \s: space/ \d:number / \[-]...

p = re.compile("^jupyter") #does it start from jupyter?
print (bool(p.search("jupyter notebook")))
print (bool(p.search("_jupyter notebook")))
print (bool(p.search("jupy notebook")))
p = re.compile("notebook$") #does it end with notebook?
print (bool(p.search("jupyter notebook")))
print (bool(p.search("_jupyter notebook")))
print (bool(p.search("jupy notebook")))

def text_match(text):
    patterns = '^[a-z]+_[a-z]+$' #starts with a-z at least 1, need at least 1 _, [a-z] ends at least 1

    if re.search(patterns,  text):
        return 'Found a match!'
    else:
        return('Not matched!')

print(text_match("aab_cbbbc"))
print(text_match("aab_Abbbc"))
print(text_match("Aaab_abbbc"))
print(text_match("aab_aa0"))

'a.*b$' >contains a, ends with b, any character . repeated 0~infinty

"""OUTSIDE THE []"""

a$==>matches when word ends with a

^a==>matches when words start with a

.*: greedy

.*?: non greedy

. ==> anything except for \n

a{3, 5} ==> a should repeat 3,4,5 times


patterns = '\wz\w' > contains z, \w*(words repeated or not)

list.startswith() .endswith()

In [ ]:
import re
def change_date_format(dt):
    return re.sub(r'(\d{4})-(\d{1,2})-(\d{1,2})', '\\3-\\2-\\1', dt)
#for first pattern, change it to second format for object dt
# () --> 그룹
# \\n --> 순서를 부여 받은 그룹 표현, \\3: (\d{1,2}) from last, date \\w1:(\d{4}) from first, year

# \d{4} -> 반드시 숫자 4번 나와야함
# \d{1,2} -> 반드시 숫자 1번 이상 2번 이하

dt1 = "2026-01-02"
print("Original date in YYYY-MM-DD Format: ",dt1)
print("New date in DD-MM-YYYY Format: ",change_date_format(dt1))

data = "<div> <p>First</p> <p>Second</p></div>"

print(re.findall(r"<p>(.+)</p>", data)) #returns only thing in ()
print(re.findall(r"<p>(.+?)</p>", data)) #?: divides when satisfied

x = 'From john.doe@hanyang.ac.kr Sat Jan 5 09:14:16 2021 limduwon@gmail.com'
y = re.findall('\S+@\S+', x)
print(y)
y = re.findall('^From (\S+@\S+)', x) # 괄호 내부만 추출 ,search starts from "From", return (\s+@\s+)
print(y)
y = re.findall('^From .*@([^ ]*)', x) # [^문자] : 해당 문자 제외한 문자 매칭, 공백을 제외한 것 search return
print(y)
#if want to serach '$'==> use '\$'

In [ ]:
df.stack(level='col_name', or interger)
df.unstack(level='col_name' or interger)
df.swaplevel(0,1)

In [ ]:
import matplotlib.pyplot as plt
from pathlib import Path
def create_dir_save_file(dir_path: Path, url: str):
    """
    Check if the path exists and create it if it does not.
    Check if the file exists and download it if it does not.
    """
    if not dir_path.parents[0].exists():
        dir_path.parents[0].mkdir(parents=True)
        print(f'Directory Created: {dir_path.parents[0]}')
    else:
        print('Directory Exists')

    if not dir_path.exists():
        r = requests.get(url, allow_redirects=True)
        open(dir_path, 'wb').write(r.content)
        print(f'File Created: {dir_path.name}')
    else:
        print('File Exists')
    # Image file
lunar_image_url = 'https://raw.githubusercontent.com/trenton3983/DataCamp/master/Images/intro_to_data_visualization_in_python/4_3_low_contrast_mars_surface.JPG'
lunar_image_path = Path('Images/intro_to_data_visualization_in_python/4_3_low_contrast_mars_surface.JPG')
create_dir_save_file(lunar_image_path, lunar_image_url)
# Image histograms
orig = plt.imread(lunar_image_path)
pixels = orig.flatten()
plt.hist(pixels, bins=256, range=(0,256), density=True, color='blue', alpha=0.3)
plt.show()
minval, maxval = orig.min(), orig.max()
print(minval, maxval)
# Rescaling the image
plt.figure(figsize=(12, 12))

minval, maxval = orig.min(), orig.max()
print(minval, maxval)

# this is the equation from section 2.4.4
rescaled = 256*(orig - minval) / (maxval - minval) # Min-Max Scaling
# the rescaled equation from the slides is not correct
# rescaled = (255/(maxval-minval)) * (pixels - minval) # original equation
print(rescaled.min(), rescaled.max())

plt.imshow(rescaled, cmap='gray')
plt.axis('off')
plt.show()

In [ ]:
# Original and rescaled histograms
plt.hist(pixels, bins=256, range=(0,255), density=True, color='blue', alpha=0.2)
plt.hist(rescaled.flatten(), bins=256, range=(0,255), density=True, color='green', alpha=0.2)
plt.legend(['original', 'rescaled'])
plt.show()
# Image histogram and CDF
plt.hist(pixels, bins=256, range=(0,256), density=True, color='blue', alpha=0.3)
plt.twinx()
orig_cdf, bins, patches = plt.hist(pixels, cumulative=True, bins=256, range=(0,256), density=True, color='red', alpha=0.3)
#cumlative==>CDF
plt.title('Image histogram and CDF')
plt.xlim((0, 255))
plt.show()

In [ ]:
#Multiple plots on single axis
import pandas as pd

# Import matplotlib.pyplot
import matplotlib.pyplot as plt

df = pd.read_csv('datasets/percent-bachelors-degrees-women-usa.csv')
df.head()
year = df['Year']
physical_sciences = df['Physical Sciences']
computer_science = df['Computer Science']
health = df['Health Professions']
education = df['Education']
# Create a figure with 2x2 subplot layout and make the top left subplot active
plt.subplot(2, 2, 1)

# Plot in blue the % of degrees awarded to women in the Physical Sciences
plt.plot(year, physical_sciences, color='blue')
plt.title('Physical Sciences')

# Make the top right subplot active in the current 2x2 subplot grid
plt.subplot(2, 2, 2)

# Plot in red the % of degrees awarded to women in Computer Science
plt.plot(year, computer_science, color='red')
plt.title('Computer Science')

# Make the bottom left subplot active in the current 2x2 subplot grid
plt.subplot(2, 2, 3)

# Plot in green the % of degrees awarded to women in Health Professions
plt.plot(year, health, color='green')
plt.title('Health Professions')

# Make the bottom right subplot active in the current 2x2 subplot grid
plt.subplot(2, 2, 4)

# Plot in yellow the % of degrees awarded to women in the Education
plt.plot(year, education, color='yellow')
plt.title('Education')

# Improve the spacing between subplots and display them
plt.tight_layout()
plt.show()

In [ ]:
# Plot the % of degrees awarded to women in Computer Science and the Physical Sciences
plt.plot(year, computer_science, color='red')
plt.plot(year, physical_sciences, color='blue')
# Add the axis labels
plt.xlabel('Year')
plt.ylabel('Degrees awarded to women (%)')
# Set the x-axis range
plt.xlim((1990,2010))
# Set the y-axis range
plt.ylim((0,50))
# Add a title and display the plot
plt.title('Degrees awarded to women (1990-2010)\nComputer Science (red)\nPhysical Sciences (blue)')
plt.show()
# Save the image as 'xlim_and_ylim.png'
plt.savefig('xlim_and_ylim.png')

In [ ]:
#Plotting residuals of a regression

# Import plotting modules
import matplotlib.pyplot as plt
import seaborn as sns
auto = pd.read_csv('datasets/auto-mpg.csv')
auto.head()
# Generate a green residual plot of the regression between 'hp' and 'mpg'
sns.residplot(x='hp', y='mpg', data=auto, color='green') #residual, errors for each x/y

# Display the plot
plt.show()

In [ ]:
# Generate a scatter plot of 'weight' and 'mpg' using red circles
plt.scatter(auto['weight'], auto['mpg'], label='data',
            color='red', marker='o')

sns.regplot(x='weight', y='mpg', data=auto, scatter=None,
            color='blue', label='order 1')

# Plot in green a linear regression of order 2 between 'weight' and 'mpg'
sns.regplot(x='weight', y='mpg', data=auto, scatter=None, order=2,
            color='green', label='order 2') #Order: Dimesnion

plt.legend(loc='upper right')
plt.show()

In [ ]:
import pandas as pd

# Matplotlib for additional customization
from matplotlib import pyplot as plt
# display your plots inside your notebook.
%matplotlib inline

# Seaborn for plot
import seaborn as sns
df = pd.read_csv('datasets/pokemon.csv', index_col=0, encoding='ISO-8859-1')
# Melt DataFrame
stats_df = df.drop(['Total', 'Stage', 'Legendary'], axis=1)

melted_df = pd.melt(stats_df,
                    id_vars=["Name", "Type 1", "Type 2"], # Variables to keep
                    var_name="Stat") # Name of melted variable
# Enlarge the plot
plt.figure(figsize=(10,6))

# Swarmplot with melted_df
sns.swarmplot(x='Stat', y='value',
              data=melted_df,
              hue='Type 2')
plt.legend(loc='upper right')

### Quantile-Quantile Plot
- 수집 데이터를 표준정규분포이 분위수와 비교하여 그리는 그래프 --> 데이터의 정규성 가정에 대한 검토 가능하게 함

Another popular plot for checking the distribution of a data sample is the quantile-quantile plot, Q-Q plot, or QQ plot for short.

This plot generates its own sample of the idealized distribution that we are comparing with, in this case the Gaussian distribution. The idealized samples are divided into groups (e.g. 5), called quantiles. Each data point in the sample is paired with a similar member from the idealized distribution at the same cumulative distribution.

The resulting points are plotted as a scatter plot with the idealized value on the x-axis and the data sample on the y-axis.

A perfect match for the distribution will be shown by a line of dots on a 45-degree angle from the bottom left of the plot to the top right. Often a line is drawn on the plot to help make this expectation clear. Deviations by the dots from the line shows a deviation from the expected distribution.

In [ ]:
# QQ Plot
from numpy.random import seed
from numpy.random import randn
from statsmodels.graphics.gofplots import qqplot
from matplotlib import pyplot
# seed the random number generator
seed(122)
# generate univariate observations
data = 5 * randn(100) + 50
# q-q plot
qqplot(data, line='s')
pyplot.show()

In [ ]:
# Shapiro-Wilk Test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import shapiro
# seed the random number generator
seed(1)
# generate univariate observations
data = 5 * randn(100) + 50
# normality test
stat, p = shapiro(data)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
    print('Sample looks Gaussian (fail to reject H0)')
else:
    print('Sample does not look Gaussian (reject H0)')

# D'Agostino and Pearson's Test
from numpy.random import seed
from numpy.random import randn
from scipy.stats import normaltest
# seed the random number generator
seed(1)
# generate univariate observations
data = 5 * randn(100) + 50
# normality test
stat, p = normaltest(data)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
    print('Sample looks Gaussian (fail to reject H0)')
else:
    print('Sample does not look Gaussian (reject H0)')

#### Shapiro-Wilk vs. D'Agostino K^2 Test
- Shapiro-Wilk
  - 샘플 크기: Shapiro-Wilk 검정은 작은 샘플 크기에 적합하며 일반적으로 50개 미만의 샘플에 가장 효과적(그러나 최대 2000개의 샘플까지도 사용할 수 있음)
  - 민감도: 이 검정은 데이터의 정규성에 대해 매우 민감. 즉, 작은 표본에서도 비정규성을 잘 감지할 수 있음
  - 사용 상황: 작은 데이터셋을 사용할 때 또는 정규성이 중요한 정밀한 분석을 수행할 때 적합
- D'Agostino K^2 Test
  - 통계적 척도: 이 검정은 왜도와 첨도라는 두 가지 통계적 척도를 사용하여 데이터의 정규성을 평가(왜도는 대칭성의 부족을, 첨도는 꼬리의 두께를 측정)
  - 샘플 크기: D'Agostino의 K^2 검정은 상대적으로 큰 샘플 크기에 더 적합할 수 있음
  - 사용 상황: 데이터의 왜도나 첨도가 중요한 역할을 할 때, 또는 좀 더 큰 샘플 크기를 다룰 때 유용

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.distributions.empirical_distribution import ECDF
swing = pd.read_csv('https://assets.datacamp.com/production/repositories/469/datasets/e079fddb581197780e1a7b7af2aeeff7242535f0/2008_swing_states.csv')
pa_dem_share = swing.dem_share[swing.state == 'PA']
oh_dem_share = swing.dem_share[swing.state == 'OH']
pa_x= ECDF(pa_dem_share).x
pa_y= ECDF(pa_dem_share).y
oh_x= ECDF(oh_dem_share).x
oh_y= ECDF(oh_dem_share).y
plt.plot(pa_x, pa_y, marker='.', linestyle='none', label='PA')
plt.plot(oh_x, oh_y, marker='.', linestyle='none', label='OH')
plt.xlabel('Percent of vote for Obama')
plt.ylabel('ECDF')
plt.legend()
plt.show()

In [ ]:
df = pd.DataFrame({'PA': pa_dem_share.reset_index(drop=True), 'OH': oh_dem_share.reset_index(drop=True)})
df.head()
pa_oh_stats = df.agg(['mean', 'median', 'std'])
pa_oh_stats['PA - OH'] = pa_oh_stats.PA - pa_oh_stats.OH
pa_oh_stats
mean_diff = np.mean(dem_share_pa) - np.mean(dem_share_oh)
mean_diff

In [ ]:
#import library
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, log_loss
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
lol = pd.read_csv('datasets/League of Legends 2021 World Championship Play-In Groups Statistics - Raw Data.csv')